{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintMini where

-- pretty-printer generated by the BNF converter

import AbsMini
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
    PStms stms -> prPrec i 0 (concatD [prt 0 stms])

instance Print Type where
  prt i e = case e of
    Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    Type_string -> prPrec i 0 (concatD [doc (showString "string")])
    Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    Type_void -> prPrec i 0 (concatD [doc (showString "void")])

instance Print Stm where
  prt i e = case e of
    SDefi type_ assigns -> prPrec i 0 (concatD [prt 0 type_, prt 0 assigns, doc (showString ";")])
    SDecl type_ vars -> prPrec i 0 (concatD [prt 0 type_, prt 0 vars, doc (showString ";")])
    SPrint exp -> prPrec i 0 (concatD [doc (showString "print"), prt 0 exp, doc (showString ";")])
    SAssign assign -> prPrec i 0 (concatD [prt 0 assign, doc (showString ";")])
    SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
    SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    SEmpty -> prPrec i 0 (concatD [doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print Assign where
  prt i e = case e of
    Assign var exp -> prPrec i 0 (concatD [prt 0 var, doc (showString "="), prt 0 exp])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Var where
  prt i e = case e of
    Var id -> prPrec i 0 (concatD [prt 0 id])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Value where
  prt i e = case e of
    VInt n -> prPrec i 0 (concatD [prt 0 n])
    VFlo d -> prPrec i 0 (concatD [prt 0 d])
    VStr str -> prPrec i 0 (concatD [prt 0 str])

instance Print Exp where
  prt i e = case e of
    EILit n -> prPrec i 15 (concatD [prt 0 n])
    EFLit d -> prPrec i 15 (concatD [prt 0 d])
    ESLit str -> prPrec i 15 (concatD [prt 0 str])
    EBTLit -> prPrec i 15 (concatD [doc (showString "true")])
    EBFLit -> prPrec i 15 (concatD [doc (showString "false")])
    EVar var -> prPrec i 15 (concatD [prt 0 var])
    EPoInc var -> prPrec i 14 (concatD [prt 0 var, doc (showString "++")])
    EPoDec var -> prPrec i 14 (concatD [prt 0 var, doc (showString "--")])
    EPrInc var -> prPrec i 14 (concatD [doc (showString "++"), prt 0 var])
    EPrDec var -> prPrec i 14 (concatD [doc (showString "--"), prt 0 var])
    ENegate exp -> prPrec i 13 (concatD [doc (showString "-"), prt 14 exp])
    EMul exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    EAdd exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    ESub exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    EOrdLT exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<"), prt 11 exp2])
    EOrdLE exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<="), prt 11 exp2])
    EOrdGT exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">"), prt 11 exp2])
    EOrdGE exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">="), prt 11 exp2])
    EOrdEQ exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "=="), prt 9 exp2])
    EOrdNE exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "!="), prt 9 exp2])
    EConj exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 8 exp2])
    EDisj exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    EAssign assign -> prPrec i 2 (concatD [prt 0 assign])


